# Generated by Django 2.0.6 on 2018-06-30 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dxdetail',
            table='xdl_dx_special_detail',
        ),
        migrations.AlterModelTable(
            name='dxindex',
            table='xdl_dx_special_index',
        ),
        migrations.AlterModelTable(
            name='dxlist',
            table='xdl_dx_special_list',
        ),
    ]
